services:
    oneup_contao_event_generator_bundle.event_listener.calendar_event_listener:
        class: Oneup\Contao\EventGeneratorBundle\EventListener\CalendarEventListener
        public: true
        tags:
            - { name: contao.hook, hook: getAllEvents, method: onGetAllEvents, priority: 0 }

    oneup_contao_event_generator_bundle.event_listener.event_time_insert_tag_listener:
        class: Oneup\Contao\EventGeneratorBundle\EventListener\EventTimeInsertTagListener
        public: true
        tags:
            - { name: contao.hook, hook: replaceInsertTags }

    oneup_contao_event_generator_bundle.event_listener.calendar_event_generator_listener:
        class: Oneup\Contao\EventGeneratorBundle\EventListener\CalendarEventGeneratorListener
        public: true
        arguments:
            - '@database_connection'
            - '@oneup_contao_event_generator_bundle.alias_generator.event'
