services:
    oneup_contao_event_generator_bundle.alias_generator.event:
        class: Oneup\Contao\EventGeneratorBundle\Dca\Alias\EventAliasGenerator
        public: true
        arguments:
            - '@database_connection'
            - '@contao.slug'
            - '@contao.translation.translator'
