services:
    oneup_contao_event_generator_bundle.event_listener.calendar_event_generator_listener:
        class: Oneup\Contao\EventGeneratorBundle\EventListener\CalendarEventGeneratorListener
        public: true
        arguments:
            - '@database_connection'
